{{- if .Values.provider.runtimeConfig.enabled }}
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ .Values.provider.runtimeConfig.name | default "provider-runtime-config" }}
  namespace: {{ .Values.provider.namespace | default "crossplane-system" }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: provider-runtime
spec:
  {{- with .Values.provider.runtimeConfig.deployment }}
  serviceAccountTemplate:
    metadata:
      name: {{ .serviceAccountName | default "provider-helm-sa" }}
  {{- end }}
{{- end }}
