apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ .Values.provider.name | default "provider-kubernetes" }}
  namespace: {{ .Values.provider.namespace | default "crossplane-system" }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: provider
spec:
  package: {{ .Values.provider.image | default "xpkg.upbound.io/upbound/provider-kubernetes:latest" }}
  packagePullPolicy: {{ .Values.provider.packagePullPolicy | default "IfNotPresent" }}
  {{- if .Values.provider.revisionActivationPolicy }}
  revisionActivationPolicy: {{ .Values.provider.revisionActivationPolicy }}
  {{- end }}
  {{- if .Values.provider.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.provider.revisionHistoryLimit }}
  {{- end }}
  {{- if .Values.provider.skipDependencyResolution }}
  skipDependencyResolution: {{ .Values.provider.skipDependencyResolution }}
  {{- end }}
  {{- if .Values.provider.runtimeConfig.enabled }}
  controllerConfigRef:
    name: {{ .Values.provider.runtimeConfig.name | default "provider-runtime-config" }}
  {{- end }}
